print("Welcome to the MadLibs generator")
one = input("Adjective: ")
two = input("Adjective: ")
three = input("Noun: ")
four = input("Noun: ")
five = input("Plural noun: ")
six = input("Game: ")
seven = input("Plural noun: ")
eight = input("Verb ending in 'ing': ")
nine = input("Verb ending in 'ing': ")
ten = input("Plural noun: ")
eleven = input("Verb ending in 'ing': ")
twelve = input("Noun: ")
thirteen = input("Plant: ")
fourteen = input("Part of the body: ")
fifteen = input("A place: ")
sixteen = input("Verb ending in 'ing': ")
seventeen = input("Adjective: ")
eighteen = input("Number: ")
nineteen = input("Plural noun: ")

print(f"A vacation is when you take a trip to some {one} place with your {two} family. Usually you go to some place that is near a/an {three} or up a/an {four}. A good vacation place is one where you can ride {five} or play {six} or go hunting for {seven}. I like to spend my time {eight} or {nine}. When parents go on a vacation, they spend their time eating three {ten} a day, and fathers play golf, and mothers sit around {eleven}. Last summer, my little brother fell in a/an {twelve} and got poison {thirteen} all over his {fourteen}. My family is going to go to (the) {fifteen}, and I will practice {sixteen}. Parents need vacations more than kids because parents are always very {seventeen} and because they have to work {eighteen} hours every day all year making enough {nineteen} to pay for the vacation.")